### ISSUE TITLE
MPIO - Why?

### ISSUE THREAD

**Issue by jaromirk** [nmdange2/HyperV_DSC#3]
https://github.com/nmdange2/HyperV_DSC/blob/master/DSC/HyperVFabricSettings.ps1#L38-L45

**Comment by nmdange2** [comment]
I use these settings with SOFS clusters that are serving traditional SAN storage via SMB Direct, not just with Storage Spaces Direct.  So the MPIO role is there when using storage that requires multipathing.

**Comment by jaromirk** [comment]
OK, makes sense. In S2D cluster it will keep not used (VMM also installs it by default)

**Comment by nmdange2** [comment]
Yup that's why when you specify the S2D role it ensures MPIO is uninstalled

https://github.com/nmdange2/HyperV_DSC/blob/master/DSC/HyperVFabricSettings.ps1#L47-L54
